spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mac_prod
    username: mac_prod_user
    password: mac_prod_user
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: false